name: Feature Request
description: Suggest a new feature for Alpha
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe what you'd like to see.
  
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What feature would you like to see in Alpha?
    validations:
      required: true
  
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would this feature help you or others?
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any additional information, mockups, or examples
    validations:
      required: false