application:
  version: 0.9.0
  language: auto
  autoUpdates: true
  enableAnalytics: true
appearance:
  fontSize: 16
  fontFamily: Cascadia Code, Consolas, Courier New, monospace
  fontWeight: 400
  fontWeightBold: 600
  fontLigatures: true
  drawBoldTextInBrightColors: true
  lineHeight: 1
  letterSpacing: 0
  minimumContrastRatio: 1
  cursorStyle: block
  cursorBlink: true
  theme: default
  preserveBackground: true
terminal:
  defaultProfile: cmd
  renderer: default
  scrollback: 25000
  scrollOnUserInput: true
  rightClick: contextmenu
  linkHandlerKey: ctrl
  copyOnSelect: true
  trimSelection: true
  wordSeparators: ()[]{}< >/\|"'.,;
  focusOnHover: false
  preserveCWD: true
  indicatorsMode: hover
  gitStatus: true
  showTabs: single
  hideIndicators: true
  openOnStart: false
  restoreOnStart: true
  workspace: false
window:
  acrylic: false
  opacity: 1
  tabWidth: fixed
  newTabPosition: end
  contextMenuStyle: minimal
  onSecondInstance: attach
  alwaysOnTop: false
  autoHideOnBlur: false
  launchMode: default
  centerOnLaunch: false
profiles: []
workspaces: []