application:
  language: en-US
  autoUpdates: true
  gpu: false
appearance:
  fontSize: 16
  fontFamily: Menlo, Consolas, Lucida Console, monospace
  fontWeight: 400
  fontWeightBold: 600
  fontLigatures: true
  drawBoldTextInBrightColors: true
  lineHeight: 1
  letterSpacing: 0
  minimumContrastRatio: 1
  cursorStyle: block
  cursorBlink: true
terminal:
  defaultProfile: cmd
  renderer: default
  scrollback: 25000
  scrollOnUserInput: true
  rightClick: contextmenu
  linkHandlerKey: ctrl
  copyOnSelect: true
  trimSelection: true
  wordSeparators: ()[]{}< >/\|"'.,;
  focusOnHover: false
  preserveCWD: true
  openOnStart: false
  restoreOnStart: true
window:
  acrylic: false
  opacity: 1
  tabWidth: fixed
  newTabPosition: end
  onSecondInstance: attach
  alwaysOnTop: false
  autoHideOnBlur: false
  launchMode: default
  centerOnLaunch: false
profiles: []