const schema: Record<string, string> = {
  'app:profiles': 'Profiles',
  'app:settings': 'Settings',
  'app:commands': 'Show all commands',
  'app:keymaps': 'Show all keymaps',
  'terminal:create': 'New terminal',
  'terminal:clear': 'Clear terminal',
  'terminal:search': 'Search',
  'terminal:history': 'History',
  'terminal:snippets': 'Snippets',
  'terminal:copy': 'Copy',
  'terminal:paste': 'Paste',
  'terminal:select-all': 'Select all',
  'terminal:zen-mode': 'Zen mode',
  'pane:split-horizontal': 'Split horizontal',
  'pane:split-vertical': 'Split vertical',
  'pane:broadcast': 'Broadcast',
  'pane:expand': 'Expand pane',
  'pane:collapse': 'Collapse pane',
  'pane:next': 'Focus next pane',
  'pane:previous': 'Focus previous pane',
  'pane:resize-up': 'Resize pane up',
  'pane:resize-right': 'Resize pane right',
  'pane:resize-down': 'Resize pane down',
  'pane:resize-left': 'Resize pane left',
  'pane:close': 'Close pane',
  'tab:next': 'Next tab',
  'tab:previous': 'Previous tab',
  'tab:rename': 'Rename tab',
  'tab:close': 'Close tab',
  'tab:reopen-closed': 'Reopen closed tab',
  'connection:reconnect': 'Reconnect client',
  'connection:disconnect': 'Disconnect client',
  'window:create': 'New window',
  'window:close': 'Close window',
  'window:fullscreen': 'Toggle fullscreen',
  'window:devtools': 'Toggle developer tools',
  'window:toggle-visibility': 'Toggle window visibility',
};

export default schema;
