import { z } from 'zod';

import type { Profile, Settings, Workspace } from 'shared/types';

export const schema = z.object({
  application: z.object({
    version: z.string(),
    language: z.enum([
      'auto',
      'de-DE',
      'en-US',
      'es-ES',
      'fr-FR',
      'ja-JP',
      'ko-KR',
      'pt-BR',
      'ru-RU',
      'zh-CN',
    ]),
    autoUpdates: z.boolean(),
    enableAnalytics: z.boolean(),
  }),
  appearance: z.object({
    fontSize: z.number().min(1).max(99),
    fontFamily: z.string(),
    fontWeight: z.number().min(100).max(900),
    fontWeightBold: z.number(),
    fontLigatures: z.boolean(),
    drawBoldTextInBrightColors: z.boolean(),
    lineHeight: z.number().min(1).max(99),
    letterSpacing: z.number().min(-10).max(10),
    minimumContrastRatio: z.number().min(1).max(21),
    cursorStyle: z.enum(['block', 'bar', 'underline']),
    cursorBlink: z.boolean(),
    theme: z.string(),
    preserveBackground: z.boolean(),
  }),
  terminal: z.object({
    renderer: z.enum(['dom', 'webgl', 'canvas']),
    scrollback: z.number().min(0).max(50000),
    scrollOnUserInput: z.boolean(),
    rightClick: z.enum(['contextmenu', 'clipboard']).nullable(),
    linkHandlerKey: z.enum(['ctrl', 'shift', 'alt', 'meta']).nullable(),
    copyOnSelect: z.boolean(),
    trimSelection: z.boolean(),
    wordSeparators: z.string(),
    focusOnHover: z.boolean(),
    preserveCWD: z.boolean(),
    indicatorsMode: z.enum(['always', 'hover', 'hidden']),
    gitStatus: z.boolean(),
    showTabs: z.enum(['single', 'multiple', 'hidden']),
    hideIndicators: z.boolean(),
    openOnStart: z.boolean(),
    restoreOnStart: z.boolean(),
    defaultProfile: z.string(),
    workspace: z.string().nullable(),
  }),
  window: z.object({
    acrylic: z.boolean(),
    opacity: z.number().min(0).max(1),
    tabWidth: z.enum(['auto', 'fixed']),
    newTabPosition: z.enum(['after-current', 'end']),
    contextMenuStyle: z.enum(['minimal', 'detailed']),
    onSecondInstance: z.enum(['attach', 'new-window']),
    alwaysOnTop: z.boolean(),
    autoHideOnBlur: z.boolean(),
    launchMode: z.enum(['default', 'maximized', 'fullscreen']),
    centerOnLaunch: z.boolean(),
  }),
  profiles: z.array(z.custom<Profile>()),
  workspaces: z.array(z.custom<Workspace>()),
});

export function defaultSettings(): Settings {
  return {
    application: {
      version: process.env.npm_package_version!,
      language: 'auto',
      autoUpdates: true,
      enableAnalytics: true,
    },
    appearance: {
      fontSize: 16,
      fontFamily: 'Cascadia Code, Consolas, monospace',
      fontWeight: 400,
      fontWeightBold: 600,
      fontLigatures: true,
      drawBoldTextInBrightColors: true,
      lineHeight: 1,
      letterSpacing: 0,
      minimumContrastRatio: 1,
      cursorStyle: 'block',
      cursorBlink: true,
      theme: 'default',
      preserveBackground: true,
    },
    terminal: {
      renderer: 'dom',
      scrollback: 25000,
      scrollOnUserInput: true,
      rightClick: 'contextmenu',
      linkHandlerKey: 'ctrl',
      copyOnSelect: true,
      trimSelection: true,
      wordSeparators: '()[]{}< >/\\|"\'.,;',
      focusOnHover: false,
      preserveCWD: true,
      indicatorsMode: 'hover',
      gitStatus: true,
      showTabs: 'single',
      hideIndicators: true,
      openOnStart: false,
      restoreOnStart: true,
      defaultProfile: 'clink',
      workspace: null,
    },
    window: {
      acrylic: false,
      opacity: 1,
      tabWidth: 'fixed',
      newTabPosition: 'after-current',
      contextMenuStyle: 'minimal',
      onSecondInstance: 'new-window',
      alwaysOnTop: false,
      autoHideOnBlur: false,
      launchMode: 'default',
      centerOnLaunch: false,
    },
    profiles: [],
    workspaces: [],
  } satisfies Settings;
}
