name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build

      - name: Install Chromium for Playwright
        run: bunx playwright install chromium --with-deps

      - name: Run tests
        run: bunx playwright test